### ISSUE TITLE
Is there a timeline for the release 3.0?

### ISSUE THREAD

**Issue by hding2455** [CAMMA-public/cholect50#5]
Thank you for your great data!

Is there a timeline for the release 3.0 which contains the bounding box annotation?

**Comment by abdksyed** [comment]
Are there any updates on releasing the bounding box for training data?

**Comment by labdeeman7** [comment]
Could we collaborate with the authors to expedite the release of the bounding box dataset

**Comment by nwoyecid** [comment]
Yes, the bounding boxes will be released very soon!

**Comment by NGC2237-cn** [comment]
Sorry, could we obtain the  training data with bounding box now?

**Comment by lennart-maack** [comment]
Is the training data including the bounding boxes already released?

**Comment by nwoyecid** [comment]
The bounding box labels will be released in CholecTrack20 dataset:  https://github.com/CAMMA-public/cholectrack20
