### ISSUE TITLE
evaluation protocol

### ISSUE THREAD

**Issue by Lycus99** [CAMMA-public/cholect50#7]
Thanks for the challenge and the benchmark. 
In Section 5.2 (evaluation protocol) of the paper, you say "For method ranking, the challenge evaluation is performed on 94 valid triplet classes excluding the 6 null classes in the dataset". 
The mAP_ivt score of RDV is 32.7%. Does it mean the mAP_ivt score of the 6 null classes is not included in the final result? 
mAP_ivt = (mAP_t0+mAP_t2+...mAP_t93)/94

**Comment by nwoyecid** [comment]
Use ivtmetrics to simplify your life.
