### ISSUE TITLE
get_binary_labels return phase label as well

### ISSUE THREAD

**Issue by cypher004** [CAMMA-public/cholect50#8]
the get_binary_labels function returns 5 values (labels) including the phase label.

However the section "Code: reading the dataset during experiment:" indicates that we should expect 4 labels from the dataloader.

The ordering of the remaining (original 4) is also different from the one indicated in "Code: reading the dataset during experiment:" section. (And in the RDV model's code)

**Comment by nwoyecid** [comment]
Dear user,
The new dataset (CholecT50)'s format include the phase label, you can ignore this if you are not interested in the phase labels. 
Thanks
